/*
 * File Name: TriggerException.cls
 * Description: Implements best practices for trigger: http://developer.force.com/cookbook/recipe/trigger-pattern-for-tidy-streamlined-bulkified-triggers
 * 
 * Modification Log
================================================================================
 * Ver		Date			Author					Modification
--------------------------------------------------------------------------------
 * 1.0		12/19/2014		Bluescape
*/

public class TriggerException extends Exception {

}